site_name: "AG-PSSG-TESTDOC"
site_description: "This is base test techdoc for AG and PSSG"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/ag-sso-terraform"
edit_uri: edit/develop/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
